In [1]:
import numpy as np

In [2]:
data = np.genfromtxt('iris.csv', delimiter=',', skip_header=1, usecols=(0,1,2,3))


In [3]:
print(f"shape:{data.shape}")

shape:(150, 4)


In [4]:
print("mean per column:",np.mean(data,axis=0))

mean per column: [75.5         5.84333333  3.054       3.75866667]


In [5]:
print("max per column:",np.max(data,axis=0))
print("min per column:",np.min(data,axis=0))

max per column: [150.    7.9   4.4   6.9]
min per column: [1.  4.3 2.  1. ]


In [6]:
print("std per column:",np.std(data,axis=0))#Variance ka square root hota hai, isliye result wapas normal units mein aata hai.
#“Yeh data set stable hai ya har value random idhar udhar ja rahi hai?”

std per column: [43.30030793  0.82530129  0.43214658  1.75852918]


In [7]:
print("var per column:",np.var(data,axis=0))#	Har value aur average ke darmiyan difference ka square karta hai
#  Variance aur Standard Deviation se pata chalta hai ke data “mean” ke around kitna idhar-udhar bhatak raha hai 

var per column: [1.87491667e+03 6.81122222e-01 1.86750667e-01 3.09242489e+00]


In [8]:
z_score = (data - np.mean(data, axis=0)) / np.std(data, axis=0)#Sabhi features ko ek jaise scale pe lana hota hai, 
#warna kuch features jyada "weight" le lete hain
print("Z-score normalized data:\n", z_score)

Z-score normalized data:
 [[-1.72054204 -0.90068117  1.03205722 -1.3412724 ]
 [-1.69744751 -1.14301691 -0.1249576  -1.3412724 ]
 [-1.67435299 -1.38535265  0.33784833 -1.39813811]
 [-1.65125846 -1.50652052  0.10644536 -1.2844067 ]
 [-1.62816394 -1.02184904  1.26346019 -1.3412724 ]
 [-1.60506942 -0.53717756  1.95766909 -1.17067529]
 [-1.58197489 -1.50652052  0.80065426 -1.3412724 ]
 [-1.55888037 -1.02184904  0.80065426 -1.2844067 ]
 [-1.53578584 -1.74885626 -0.35636057 -1.3412724 ]
 [-1.51269132 -1.14301691  0.10644536 -1.2844067 ]
 [-1.4895968  -0.53717756  1.49486315 -1.2844067 ]
 [-1.46650227 -1.26418478  0.80065426 -1.227541  ]
 [-1.44340775 -1.26418478 -0.1249576  -1.3412724 ]
 [-1.42031323 -1.87002413 -0.1249576  -1.51186952]
 [-1.3972187  -0.05250608  2.18907205 -1.45500381]
 [-1.37412418 -0.17367395  3.11468391 -1.2844067 ]
 [-1.35102965 -0.53717756  1.95766909 -1.39813811]
 [-1.32793513 -0.90068117  1.03205722 -1.3412724 ]
 [-1.30484061 -0.17367395  1.72626612 -1.17067529]
 [-1.

**Standard Deviation (std):**  
Data points ka mean se kitna farq hai, yeh dikhata hai.

**Variance (var):**  
Data points ke difference ka square karke spread ko measure karta hai.

**Z-score:**  
Yeh batata hai ke data point mean se kitni doori par hai, standard deviation ke hisaab se.

In [9]:
# Sepal Length column
sepal_length = data[:, 0]
print("Sepal Length:", sepal_length)

# First 10 flowers
first_10 = data[:10]
print("First 10 rows:\n", first_10)

# Petal Length > 1.5
petal_length_filtered = data[data[:, 2] > 1.5]
print("Filtered (Petal Length > 1.5):\n", petal_length_filtered)


Sepal Length: [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150.]
First 10 rows:
 [[ 1.   5.1  3.5  1.4]
 [ 2.   4.9  3.   1.4]
 [ 3.   4.7  3.2  1.3]
 [ 4.   4.6  3.1  1.5]
 [ 5.   5.   3.6  1.4]
 [ 6.   5.4  3.9  1.7]
 [ 7.   4.6  3.4  1.4]
 [ 8.   5.   3.4  1.5]
 [ 9.   4.4  2.9  1.4]
 

In [10]:
# Euclidean distance between first two rows
dist = np.linalg.norm(data[0] - data[1])
print("Euclidean distance between first two flowers:", dist)

# Count Sepal Width > mean
mean_sepal_width = np.mean(data[:, 1])
count_greater = np.sum(data[:, 1] > mean_sepal_width)
print("Count where Sepal Width > mean:", count_greater)

# Element-wise multiplication: SepalLength * PetalLength
multiplied = data[:, 0] * data[:, 2]
print("SepalLength * PetalLength:\n", multiplied)


Euclidean distance between first two flowers: 1.1357816691600546
Count where Sepal Width > mean: 70
SepalLength * PetalLength:
 [  3.5   6.    9.6  12.4  18.   23.4  23.8  27.2  26.1  31.   40.7  40.8
  39.   42.   60.   70.4  66.3  63.   72.2  76.   71.4  81.4  82.8  79.2
  85.   78.   91.8  98.   98.6  96.   96.1 108.8 135.3 142.8 108.5 115.2
 129.5 117.8 117.  136.  143.5  96.6 137.6 154.  171.  138.  178.6 153.6
 181.3 165.  163.2 166.4 164.3 124.2 154.  156.8 188.1 139.2 171.1 162.
 122.  186.  138.6 185.6 188.5 204.6 201.  183.6 151.8 175.  227.2 201.6
 182.5 207.2 217.5 228.  215.6 234.  229.1 208.  194.4 196.8 224.1 226.8
 255.  292.4 269.7 202.4 267.  225.  236.6 276.  241.8 216.2 256.5 288.
 281.3 284.2 247.5 280.  333.3 275.4 309.  301.6 315.  318.  267.5 313.2
 272.5 396.  355.2 302.4 339.  285.  322.  371.2 351.  448.4 309.4 264.
 387.2 341.6 344.4 334.8 412.5 403.2 355.6 384.  361.2 390.  366.8 501.6
 372.4 375.2 351.  408.  465.8 427.8 417.  434.  437.1 440.2 386.1 460.8

np.linalg.norm(...)Yeh numpy ka function hai jo vector ka length (magnitude) calculate karta hai.

Aur jab aap 2 points ke difference ka norm nikalte ho, to woh ban jata hai:

In [12]:
# Reshape into batches of 30
reshaped = data.reshape(-1, 30, 4)
print("Reshaped data shape:", reshaped.shape)

# Stack SepalLength and PetalLength
stacked = np.column_stack((data[:, 0], data[:, 2]))
print("Stacked SepalLength & PetalLength:\n", stacked)

# Boolean mask for PetalWidth < 0.5
mask = data[:, 3] < 0.5
filtered_rows = data[mask]
print("mask",mask)
print("Filtered rows (PetalWidth < 0.5):\n", filtered_rows)


Reshaped data shape: (5, 30, 4)
Stacked SepalLength & PetalLength:
 [[  1.    3.5]
 [  2.    3. ]
 [  3.    3.2]
 [  4.    3.1]
 [  5.    3.6]
 [  6.    3.9]
 [  7.    3.4]
 [  8.    3.4]
 [  9.    2.9]
 [ 10.    3.1]
 [ 11.    3.7]
 [ 12.    3.4]
 [ 13.    3. ]
 [ 14.    3. ]
 [ 15.    4. ]
 [ 16.    4.4]
 [ 17.    3.9]
 [ 18.    3.5]
 [ 19.    3.8]
 [ 20.    3.8]
 [ 21.    3.4]
 [ 22.    3.7]
 [ 23.    3.6]
 [ 24.    3.3]
 [ 25.    3.4]
 [ 26.    3. ]
 [ 27.    3.4]
 [ 28.    3.5]
 [ 29.    3.4]
 [ 30.    3.2]
 [ 31.    3.1]
 [ 32.    3.4]
 [ 33.    4.1]
 [ 34.    4.2]
 [ 35.    3.1]
 [ 36.    3.2]
 [ 37.    3.5]
 [ 38.    3.1]
 [ 39.    3. ]
 [ 40.    3.4]
 [ 41.    3.5]
 [ 42.    2.3]
 [ 43.    3.2]
 [ 44.    3.5]
 [ 45.    3.8]
 [ 46.    3. ]
 [ 47.    3.8]
 [ 48.    3.2]
 [ 49.    3.7]
 [ 50.    3.3]
 [ 51.    3.2]
 [ 52.    3.2]
 [ 53.    3.1]
 [ 54.    2.3]
 [ 55.    2.8]
 [ 56.    2.8]
 [ 57.    3.3]
 [ 58.    2.4]
 [ 59.    2.9]
 [ 60.    2.7]
 [ 61.    2. ]
 [ 62.    3. ]
 [